# --- !Ups

UPDATE NOTIFICATION_EVENT
set event_type = 'PULL_REQUEST_MERGED'
, OLD_VALUE = NEW_VALUE
, NEW_VALUE = 'conflict'
WHERE EVENT_TYPE = 'PULL_REQUEST_CONFLICTS'

# --- !Downs

UPDATE NOTIFICATION_EVENT
set event_type = 'PULL_REQUEST_CONFLICTS'
, NEW_VALUE = OLD_VALUE
, OLD_VALUE = ''
WHERE EVENT_TYPE = 'PULL_REQUEST_MERGED'
AND NEW_VALUE = 'conflict'
