# --- !Ups
ALTER TABLE ISSUE_COMMENT ADD COLUMN CONTENTS_BAK varchar(4000);
UPDATE ISSUE_COMMENT ic1 set CONTENTS_BAK = (SELECT CONTENTS FROM ISSUE_COMMENT ic2 where ic2.id = ic1.id);
ALTER TABLE ISSUE_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE ISSUE_COMMENT ADD COLUMN CONTENTS clob;
UPDATE ISSUE_COMMENT ic1 set CONTENTS = (SELECT CONTENTS_BAK FROM ISSUE_COMMENT ic2 where ic2.id = ic1.id);
ALTER TABLE ISSUE_COMMENT DROP COLUMN CONTENTS_BAK;

ALTER TABLE POSTING_COMMENT ADD COLUMN CONTENTS_BAK varchar(4000);
UPDATE POSTING_COMMENT pc1 set CONTENTS_BAK = (SELECT CONTENTS FROM POSTING_COMMENT pc2 where pc2.id = pc1.id);
ALTER TABLE POSTING_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE POSTING_COMMENT ADD COLUMN CONTENTS clob;
UPDATE POSTING_COMMENT pc1 set CONTENTS = (SELECT CONTENTS_BAK FROM POSTING_COMMENT pc2 where pc2.id = pc1.id);
ALTER TABLE POSTING_COMMENT DROP COLUMN CONTENTS_BAK;

ALTER TABLE COMMIT_COMMENT ADD COLUMN CONTENTS_BAK varchar(4000);
UPDATE COMMIT_COMMENT cc1 set CONTENTS_BAK = (SELECT CONTENTS FROM COMMIT_COMMENT cc2 where cc2.id = cc1.id);
ALTER TABLE COMMIT_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE COMMIT_COMMENT ADD COLUMN CONTENTS clob;
UPDATE COMMIT_COMMENT cc1 set CONTENTS = (SELECT CONTENTS_BAK FROM COMMIT_COMMENT cc2 where cc2.id = cc1.id);
ALTER TABLE COMMIT_COMMENT DROP COLUMN CONTENTS_BAK;

ALTER TABLE PULL_REQUEST_COMMENT ADD COLUMN CONTENTS_BAK varchar(4000);
UPDATE PULL_REQUEST_COMMENT prc1 set CONTENTS_BAK = (SELECT CONTENTS FROM PULL_REQUEST_COMMENT prc2 where prc2.id = prc1.id);
ALTER TABLE PULL_REQUEST_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE PULL_REQUEST_COMMENT ADD COLUMN CONTENTS clob;
UPDATE PULL_REQUEST_COMMENT prc1 set CONTENTS = (SELECT CONTENTS_BAK FROM PULL_REQUEST_COMMENT prc2 where prc2.id = prc1.id);
ALTER TABLE PULL_REQUEST_COMMENT DROP COLUMN CONTENTS_BAK;

# --- !Downs
ALTER TABLE ISSUE_COMMENT ADD COLUMN CONTENTS_BAK clob;
UPDATE ISSUE_COMMENT ic1 set CONTENTS_BAK = (SELECT CONTENTS FROM ISSUE_COMMENT ic2 where ic2.id = ic1.id);
ALTER TABLE ISSUE_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE ISSUE_COMMENT ADD COLUMN CONTENTS varchar(4000);
UPDATE ISSUE_COMMENT ic1 set CONTENTS = (SELECT CONTENTS_BAK FROM ISSUE_COMMENT ic2 where ic2.id = ic1.id);
ALTER TABLE ISSUE_COMMENT DROP COLUMN CONTENTS_BAK;

ALTER TABLE POSTING_COMMENT ADD COLUMN CONTENTS_BAK clob;
UPDATE POSTING_COMMENT pc1 set CONTENTS_BAK = (SELECT CONTENTS FROM POSTING_COMMENT pc2 where pc2.id = pc1.id);
ALTER TABLE POSTING_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE POSTING_COMMENT ADD COLUMN CONTENTS varchar(4000);
UPDATE POSTING_COMMENT pc1 set CONTENTS = (SELECT CONTENTS_BAK FROM POSTING_COMMENT pc2 where pc2.id = pc1.id);
ALTER TABLE POSTING_COMMENT DROP COLUMN CONTENTS_BAK;

ALTER TABLE COMMIT_COMMENT ADD COLUMN CONTENTS_BAK clob;
UPDATE COMMIT_COMMENT cc1 set CONTENTS_BAK = (SELECT CONTENTS FROM COMMIT_COMMENT cc2 where cc2.id = cc1.id);
ALTER TABLE COMMIT_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE COMMIT_COMMENT ADD COLUMN CONTENTS varchar(4000);
UPDATE COMMIT_COMMENT cc1 set CONTENTS = (SELECT CONTENTS_BAK FROM COMMIT_COMMENT cc2 where cc2.id = cc1.id);
ALTER TABLE COMMIT_COMMENT DROP COLUMN CONTENTS_BAK;

ALTER TABLE PULL_REQUEST_COMMENT ADD COLUMN CONTENTS_BAK clob;
UPDATE PULL_REQUEST_COMMENT prc1 set CONTENTS_BAK = (SELECT CONTENTS FROM PULL_REQUEST_COMMENT prc2 where prc2.id = prc1.id);
ALTER TABLE PULL_REQUEST_COMMENT DROP COLUMN CONTENTS;
ALTER TABLE PULL_REQUEST_COMMENT ADD COLUMN CONTENTS varchar(4000);
UPDATE PULL_REQUEST_COMMENT prc1 set CONTENTS = (SELECT CONTENTS_BAK FROM PULL_REQUEST_COMMENT prc2 where prc2.id = prc1.id);
ALTER TABLE PULL_REQUEST_COMMENT DROP COLUMN CONTENTS_BAK;
