package models.enumeration;

public enum NotificationType {
    NEW_ISSUE, NEW_POSTING, ISSUE_ASSIGNEE_CHANGED, ISSUE_STATE_CHANGED, NEW_COMMENT, NEW_PULL_REQUEST, NEW_SIMPLE_COMMENT, PULL_REQUEST_STATE_CHANGED
}
